### ISSUE TITLE
doxygen config file to generate the html/pdf/man documentation

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#25]
Greetings, Matteo,

in Debian, we cannot ship already formed documentation files. We want to be able to build the documentation "live", while the package is created in the Debian autobuilder structure. 

Could you please provide us in the source tree with the doxygen configuration file and the command you run to build the documentation?

Since the documentation is indeed extracted from the source code, why not put a doc target in the Makefile that would do the job?

Thank you for your consideration,
Cheers,
Filippo

**Comment by lopippo** [comment]
Greetings from the Packaging for Debian Department:

I can generate the doxygen-based documentation for IsoSpec++ with the attached configuration file that should be located in the man subdirectory. To build the documentation exactly as previously done, just run from the top source directory the following command:
doxygen man/isospec_docs. That will create man/html and man/latex just fine.

Would you consider putting the attached file as is in top_src_dir/man so that it is there for the next releases ?

I had to rename the file with a .txt extension because GitHub would not recognize a file name with no extension. Then I took the liberty to rename it from isospec_docs to something more functionally meaning. Feel free to rename it to whatever you like :-)

[doxyfile.txt](https://github.com/MatteoLacki/IsoSpec/files/2773218/doxyfile.txt)

Cheers,
Filippo

**Comment by michalsta** [comment]
Hi,

The file is included. Thanks!

**Comment by lopippo** [comment]
Greetings, 
looks fine, I'll close the issue, then.
Cheers,
Filippo
