### ISSUE TITLE
This is not an issue, but a suggestion

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#28]
Greetings,

I have successfully integrated Isospec functionalities in my msXpertSuite software. I build MacOSX ports of all my software and I thus need to build libIsoSpec++ under my macport environment.

The following Makefile target works fine (build and link and executable linking to the share lib all work):

macports:
\tab$(CXX) $(CXXFLAGS) $(OPTFLAGS) unity-build.cpp -fPIC -dynamiclib -o /opt/local/lib/libIsoSpec++.dylib

In order to make the software more portable and to give hints to potential Mac users, would you like to add that target to the IsoSpec++  Makefile?

Cheers,
Filippo

PS I guess -fPIC is not required. But it does no harm.

**Comment by michalsta** [comment]
Seems obsolete with the new cmake build system
