### ISSUE TITLE
More python 3(.6) changes and not sure of output with python 3.6

### ISSUE THREAD

**Issue by jostheim** [MatteoLacki/IsoSpec#3]
I think you need to change:

`symbol_to_masses[symbol] += (isoFFI.clib.elem_table_mass[i],)
    symbol_to_probs[symbol] += (isoFFI.clib.elem_table_probability[i],)
    symbol_to_atomic_number[symbol] = isoFFI.clib.elem_table_atomicNo[i]`

to 

`symbol_to_masses[symbol.decode('UTF-8')] += (isoFFI.clib.elem_table_mass[i],)
    symbol_to_probs[symbol.decode('UTF-8')] += (isoFFI.clib.elem_table_probability[i],)
    symbol_to_atomic_number[symbol.decode('UTF-8')] = isoFFI.clib.elem_table_atomicNo[i]`

all the symbols from PeriodicTable seem to be bytes, not strings.  Also I tried to run this on Glutathione:

```
i = IsoSpecPy.IsoSpec.IsoFromFormula("C10H17N3O6S1", 1E-19)

print("The isotopologue set containing at least 1E-9 probability has", len(i), "element(s)")

confs = i.getConfs()
print(confs)
```

and got:

`The isotopologue set containing at least 1E-19 probability has 1 element(s)
([307.08380645649], [-0.18744310259840802], [])`

Glutathione definitely has more isotopologues than that.  From a very simple version of calculating isotopes I get:

```
{307: [307.08380598389977, 0.8292611179003183],
 308: [308.08644510139936, 0.10903518083563768],
 309: [309.08234444892486, 0.05433925423498538],
 310: [310.08459188181274, 0.0062162033379672705],
 311: [311.08458381763955, 0.001040023201284577],
 312: [312.0865777272728, 9.758434768200495e-05],
 313: [313.0876550940838, 9.828675479095363e-06],
 314: [314.0895609833712, 7.483793727480966e-07],
 315: [315.0911703622976, 5.3583021898102345e-08],
 316: [316.0942878787752, 5.032390015613561e-10]}
```

**Comment by jostheim** [comment]
Actually I see you are decoding in the non-pypi version, the pip install doesn't work for 3.6, i still don't get a resonable number of isotopes for glutathione.

**Comment by michalsta** [comment]
Hi,

First, apologies for the delayed response, must have missed the notification email...

We have already (in the meantime) backported the decoding to the pypi version, and now it should work with python3.6.

Regarding the issues with glutathione, however, it's a simple mistake: 
what you actually probably want is not 1E-19 as argument, but 1.0 - 1E-19

The default algorithm in 1.0.X calculates the smallest set which covers at least as much probability as the argument. If the argument is tiny then just one configuration is enough to go over the threshold and the algorithm terminates. The argument to get a reasonable cover is therefore "almost 1.0" (like 0.999) and not "almost 0.0". 

Note that this is different in the "thresholding" version of the algorithm, for them the standard arguments are "close to zero".
