### ISSUE TITLE
DLL API export "can of worms"

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#36]
Greetings, 

I have had to provide some #define's in case the lib is built in WIN. Specifically, I tried to build on what the OpenMS guys did, so as to be the least intrusive (platform.h).

Hope you'll accept these modifs that are necessary for the lib to be really useful in WIN settings.

Feel free to close this issue.

EDIT: apparently there are some glitches that I need to fix.
EDIT: forget about all this bullshit. The library builds fine and is usable. I have reverted the changes. Sorry for the noise.

Cheers,
Filippo

**Comment by michalsta** [comment]
Right ;)
