### ISSUE TITLE
/usr/lib/python3/dist-packages/IsoSpecPy/IsoSpecPy.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#40]
Greetings, and happier new year :-)

Just to tell you that I have this warning message. Nothing serious...

/usr/lib/python3/dist-packages/IsoSpecPy/IsoSpecPy.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?

Cheers,
Filippo

**Comment by michalsta** [comment]
Thanks for the heads up. Seems it's a new warning in Python3.8. We've fixed it in git as of now, and it'll be included in the next release.

**Comment by michalsta** [comment]
Thanks for the heads up. Seems it's a new warning in Python3.8. We've fixed it in git as of now, and it'll be included in the next release.

**Comment by michalsta** [comment]
Fixed by 67eb8de
