### ISSUE TITLE
Compatibility issue with openSUSE Linux Leap 15.3

### ISSUE THREAD

**Issue by daneletourneau** [MatteoLacki/IsoSpec#42]
I am running openSUSE Leap 15.3, with Python 3.6.15 running in a virtual environment. I was having major issues trying to get IsoSpec to run in this scenario, as it was throwing warnings about not being able to find the C++ part of the software. After some fiddling, I managed to figure out that the libIsoSpec++.so file was not getting copied into the ".egg" library in the virtual environment when IsoSpec was installed. Copying this seemed to solve the issue. I've summarized the exact steps I took to restore functionality below:

- Clone IsoSpec.git from repository
- cd into IsoSpec folder
- Run python3 setup.py install (with virtual environment activated if you're using one)
- copy libIsoSpec++.so into venv/lib64/python3.6/site-packages/IsoSpecPy-2.2.0-py3.6-linux-x86_64.egg/IsoSpecPy folder

**Comment by michalsta** [comment]
Hi,

I can't reproduce the error. Could you outline the exact steps you're taking that lead to it? Do you create a clean, empty venv? Is your arch x86_64? Is that OpenSUSE on bare metal or a docker image? Would be perfect if you could reproduce this error in a clean docker iamge and post a step-by-step instruction :)

**Comment by daneletourneau** [comment]
Hello,

I have been looking into this further, it may be that this was the result of something else that was not configured properly with my system. I am investigating further, and will close this issue if I can confirm that this wasn't a universal problem!
