### ISSUE TITLE
Question: -dev suffixed tags suitable for Debian release ?

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#46]
Greetings! (long time no hear :-)

I was planning to package the latest tag-version of libIsoSpec++ for the next Debian release, but then I saw the suffix -dev. Do these tags correspond to stable software ?

Sincerely,
Filippo

**Comment by michalsta** [comment]
Okay, well, this is kind of embarassing, the 2.2.0 tag seems to have been lost somewhere. No matter, I guess it's time to do a 2.2.1 release, please just use that. And very definitely not the -dev tags ;)

**Comment by lopippo** [comment]
Greetings Michał,

Ok, so let's say that you will close this issue when the tag will be available. This way I'll know I can fetch it right away. Thank you! 

Sincerely,
Filippo

**Comment by michalsta** [comment]
OK, it is done ;)
