### ISSUE TITLE
Error in the comment  IsoSpec/IsoSpec++/isoSpec++.h  line 67

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#48]
Greetings,

I suspect the comment below should have read H2O (water) in steal of H20 (twenty hydrogen atoms). Or am I wrong?

int             allDim;         /*!< The total number of isotopes of elements present in a chemical formula, e.g. for H20 it is 2+3=5. */

Thanks for this amaizing software!
Sincerely
Filippo

**Comment by MatteoLacki** [comment]
Hello,

Sure, it was supposed to be H2O. I have a terrible problem with this
particular typo, as not all fonts have a good distinction between the two...
The calculation would make obviously no sense for H20.

Best wishes,

*Mateusz Krzysztof Łącki*

tel. +49 159 01681376

GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by michalsta** [comment]
Woah, nicely spotted, thanks. Fixed by a67cd33758b14c9c11e5903b5e94133149f4acd9
