### ISSUE TITLE
The C++ example does not seem to work

### ISSUE THREAD

**Issue by lopippo** [MatteoLacki/IsoSpec#7]
Greetings, 
following the COMPILATION instructions, I get the following output:

(ins)rusconi@roma:~/devel/packaging/isospec/tarballs/isospec/Examples/C++$ clang++ -std=c++11 -lIsoSpec++ -L. water.cpp
water.cpp:7:5: error: unknown type name 'IsoSpec'
    IsoSpec* iso = IsoSpec::IsoFromFormula("H2O1", 0.9);
    ^
water.cpp:7:20: error: use of undeclared identifier 'IsoSpec'
    IsoSpec* iso = IsoSpec::IsoFromFormula("H2O1", 0.9);
                   ^
water.cpp:57:15: error: unknown type name 'IsoSpecLayered'
    iso = new IsoSpecLayered(elementNumber, isotopeNumbers, atomCounts, isotope_masses, probs, 0.9);
              ^
3 errors generated.

Further: when I change directory to IsoSpec++ and I run

grep IsoFromFormula *

I do not get any output. 

I can build the shared library.

git status in the master branch is ok.

What could I be missing?
Thank you very much for providing this library.
Filippo

**Comment by michalsta** [comment]
Hi,

The example has lagged a bit behind the codebase - it targetted the 1.0.X API, while the repo is in 1.9.0alpha stage. I have fixed that though, it should work now.

**Comment by michalsta** [comment]
Yes, in fact, since there seems to be a flurry of interest lately, I think
that we'll try to get the repo in shape to push out the 1.9.0 (stable,
non-alpha) release sometime in the next week, and that of course will
include some sensible documentation, among other things. Will that be okay
with whatever timelines you have to keep?

**Comment by lopippo** [comment]
> Yes, in fact, since there seems to be a flurry of interest lately, I think that we'll try to get the repo in shape to push out the 1.9.0 (stable, non-alpha) release sometime in the next week, and that of course will include some sensible documentation, among other things. Will that be okay with whatever timelines you have to keep?

Thank you very much. That would be perfect. Packaging -at least as C++ lib- should be very straighforward.

Sincerely,
Filippo

**Comment by michalsta** [comment]
Hi,

We have just now tagged and released a 1.9.0, along with documentation and fixed examples (and several bugfixes too). Sorry it took much longer than projected ;)

Anyway, if you still want to package it, now would be a good moment. Of course feel free to contact us if you have any questions/other issues!

**Comment by lopippo** [comment]
Greetings, Matteo,


On Wed, Nov 07, 2018 at 01:04:27PM -0800, michalsta wrote:
>We have just now tagged and released a 1.9.0, along with documentation and fixed examples (and several bugfixes too). Sorry it took much longer than projected ;)
>
>Anyway, if you still want to package it, now would be a good moment. Of course feel free to contact us if you have any questions/other issues!

Thank you so much for this update.

I would be very grateful if you would take some time to write a small manual
with some typical usecases (proteins, peptides, small molecules), just show the
command line, the formula to crunch, the textual output and how it translates
into a super isotopic cluster.

Sorry for asking this, but I find it essential that users (myself in it) can be put at work with nice examples. 

Do you know docbook ? If you write that document, I could format it in docbook
so that we can generate pdf / html version of it.

Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
          http://www.debian.org

~~~~
book: http://www.lavoisier.fr/livre/notice.asp?id=3LKW2OAR2KROWZ
http://books.google.fr/books?id=2NmguxmEI1sC&printsec=frontcover&dq=rusconi+f+lavoisier&hl=fr&sa=X&ei=nGGOUt2SH_Ly0gX0uIHoBQ&ved=0CDUQ6AEwAA#v=onepage&q&f=false
~~~~
Génétique Quantitative et Évolution & Plateforme PAPPSO
UMR CNRS 8120 – INRA – Université Paris-Sud – AgroParisTech - Université Paris-Saclay
http://moulon.inra.fr/ & http://pappso.inra.fr/
Ferme du Moulon
91190 Gif-sur-Yvette
France
Tel : +33 (0)1 69 33 23 68
Fax : +33 (0)1 69 33 23 40

**Comment by MatteoLacki** [comment]
Hello Filippo,

We will cook up some small examples, most likely during the weekend. I never heard of docbook.
Will simple LaTeX be enough (like, can something like pandoc translate it to docbook)? I can also write something in markdown and put it on github. Actually,
there is a webpage [already hosted there](http://matteolacki.github.io/IsoSpec/). We simply would need to update it, because it's no longer valid. 

Best,

**Comment by lopippo** [comment]
Greetings, Matteo,
sure LaTeX will be fine. 
Please, integrate in the examples, at least one detailed example for a typical peptide (15-20 residues-long) and anothe one for a protein (400 residues-long, typically). That will make your soft more appealing to massists doing top/middle-down proteomics (like I'll start doing soon ;-)

Thanks for your hard work!
Cheers,
Filippo

**Comment by lopippo** [comment]
Greetings, Matteo,

Thank you so much for the update. That's awesome. 
I have seen the new man directory, which i'll look deeper into in the next days. I feel like we are approaching the documentation level required by the Debian packaging standards. Looking forward to reading the examples to bootstrap new users right into the use of IsoSpec!
Thank you for your hard work!
Cheers,
Filippo

**Comment by MatteoLacki** [comment]
Can I say this issue is no longer valid?

**Comment by lopippo** [comment]
Certainly, I close it right now.
Thank you
Filippo
